language: php
sudo: false
php:
  - 7.2
before_script:
  - pecl install rar
  - composer self-update
  - composer install --no-interaction --prefer-source --dev
script:
  - vendor/bin/phpunit -c phpunit.xml.dist
  - vendor/bin/php-cs-fixer fix --config=.php_cs.dist -v --dry-run --stop-on-violation --using-cache=no
  - vendor/bin/phpcpd ./src --exclude ./src/Model -v
  - vendor/bin/psalm